API_ID = "TELEGRAM API ID"
API_HASH = "TELEGRAM API HASH"
BOT_TOKEN = "TELEGRAM BOT TOKEN"
DB_PATH = "PATH FOR SQLITE DATABASE"
VIDEOS_DIR = "VIDEOS_DIR"
CHAT_IDS = ["CHAT_ID"]
PROXY = dict(scheme="socks5", hostname="PROXY_HOST", port="PROXY_PORT")
